backend:
  name: github
  repo: joshatoutthink/MY_BLOG
  branch: master

media_folder: static/assets
public_folder: assets

collections:
  - name: posts
    label: Posts
    folder: posts
    create: true
    fields:
      - { name: slug, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: image, label: "Featured Image", widget: "image"}
      - { name: type, label: Type, widget: select, options:['project', 'post'] }
      - { name: body, label: Body, widget: markdown }
